### ISSUE TITLE
[FEATURE] Support spot instance hibernation

### ISSUE THREAD

**Issue by kim0** [aws-samples/aws-eda-slurm-cluster#76]
**Describe the solution you'd like**

Not sure if this is already implemented, but from scanning the code I could not find it. It would be great to add support for spot instance hibernation. i.e. For any instance where `UseSpot=true` which AWS asks to kill the instance, it would be great if the node can hibernate. Slurm would retry to bring it up repeatedly, until AWS allows it. Once the instance is back up, any running simulations on it are naturally resumed.

**Additional context**
Need to use spot instances for cost saving. Do not want to simply re-schedule interrupted jobs. This is bec, a job can be interrupted after many weeks of progress. I do not want to start over. AWS spot supports hibernation for centos/rhel-8 with some conditions (EBS disk encrypted and larger than ram ...etc). I think this can be made to work with this slurm cluster, and that would be fantastic!

**Comment by cartalla** [comment]
The following links describe spot hibernation:

* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/hibernate-spot-instances.html
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Hibernate.html

The key considerations/restrictions are the following:
'
* OS is restricted to AmazonLinux 2 and Ubuntu which aren't OSes that are supported by EDA vendors.
* Only the following instance types are supported: C3, C4, C5, M4, M5, R3, R4. Note that none of the latest generation instances are supported.
* Instance RAM must be less than 100GB

I believe that these restrictions make hibernation a poor option for EDA workloads.

There are other technical complexities with hibernating licensed applications.
When a licensed job is hibernated it will still have a license checked out which will block other jobs from running.
Depending on the license server configuration the license checkout may time out and the hibernated job will then lose its license.
When the hibernated instance resumes then if may think it may no longer have a license checked out and there may be no licenses available for checkout.
This can then cause the job to fail or to wait for a licenses (depending on job options) neither of which is desirable.

Another complexity, is that a hibernated spot instance is stopped until capacity becomes available in it's capacity pool.
If the job isn't requeued, then it may stay stuck on this node even if capacity is available in a different capacity pool. In that case you may be better off just requeuing the job so that slurm can schedule it in a capacity pool that has availability.

For these reasons we do not recommend using spot for long-running jobs that aren't fault tolerant.
Spot is ideal for running shorter jobs or jobs where requeueing is acceptable.

Synopsys did a workshop with AWS showing how to use checkpoint and restore and this is a potential option for being able to utilize spot for longer running jobs. This would involve checkpointing and then requeuing the job and then when the job is restarted detecting the checkpoint and restoring from that. The amount of memory is a limit here because it must be able to be checkpointed withing the 2 minute window.

More speculative is to use a technology like MemVerge that can cost-effectively checkpoint large amounts of memory. However, they must work with the EDA vendor on a tool-by-tool basis to qualify the tool for their technology.

**Comment by kim0** [comment]
Thanks @cartalla for this awesome response! You make some very good points. Regarding instance limitations:
* For completeness it seems RHEL/Centos-8 are [now supported](https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-ec2-hibernation-red-hat-enterprise-linux-8-centos-8-fedora-34/)
* RAM < 100GB is likely OK for my use-case
* I did not notice that I have to be using older instances, but if it'll result in huge cost savings (AWS usually mentions > 70%), which can make using those slower instances tolerable. Although it would be great to check if the newer generation is eventually getting hibernation support or not

wrt other limitations
* I was hoping with proper configuration of the license server, the license would get freed after some timeout when the instance hibernates. And hopefully the tool would be able to re-acquire the license when the instance resumes. I have not tested that in real life, but it does not sound like it can't work I think
* Re-queuing is sometimes useful, but if the job had made great progress (let's say 10 days worth), I would want it to wait instead of being killed and re-queued elsewhere

I agree ofc that having tool level support for checkpointing is likely the best options, however that might take some time. While I now have a much greater appreciation that this topic is more complex that I thought. I still think it has a chance of working.

**Comment by cartalla** [comment]
I don't plan to implement this so closing the issue.
